---
title: "Viz Critique 1"
author: "Alexandra Lalor"
date: '2022-04-06'
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
opts_chunk$set(echo = TRUE, message = F, warning = F)
```

Read in data
```{r}
fire_climate <- read_csv("data_raw/viz_critique/fire-seasonality.csv")

fire_climate[fire_climate == 0] = NA

fire_climate %>% 
  filter(!is.na(Number_Studies)) %>% 
  ggplot(aes(y = Mechanism,
             x = Number_Studies,
             fill = Climate)) +
  geom_col(position = "dodge") +
  scale_x_continuous(breaks = 0:12) +
  ggtitle("Evidence of Fire Seasonality Effects \n on Plant Population Persistence")
```

```{r}
fire_veg <- read_csv("data_raw/viz_critique/fire-seasonality-veg.csv")

fire_veg[fire_veg == 0] = NA

fire_veg %>% 
  filter(!is.na(Number_Studies)) %>% 
  ggplot(aes(y = Mechanism,
             x = Number_Studies,
             fill = Veg)) +
  geom_col() +
  scale_x_continuous(breaks = 0:20) +
  theme_minimal() +
  ggtitle("Evidence of Fire Seasonality Effects \n on Plant Population Persistence")
```

